name: Build

on:
  push:
    branches:
      - 'main'
env:
  REGISTRY: registry.lukashermansson.me
  IMAGE_NAME: lukashermansson/website-2
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: Set up bininstall
      run: |
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
        cargo binstall cargo-leptos -y
        rustup target add wasm32-unknown-unknown
        rustup target add aarch64-unknown-linux-musl
    - name: Build
      run: cargo leptos build --release -vv
      env:
        LEPTOS_BIN_TARGET_TRIPLE: aarch64-unknown-linux-musl

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log into the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Extract metadata for the Docker image
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=RELEASE-{{date 'YYYYMMDD-HHmmss'}}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        platforms: linux/arm64
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}